apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 373804767529.dkr.ecr.ap-northeast-2.amazonaws.com/mypeccy-web
  newName: 373804767529.dkr.ecr.ap-northeast-2.amazonaws.com/mypeccy-web
  newTag: 313d0442
resources:
- ../../base
patchesStrategicMerge:
- web-deployment.yaml
- web-service.yaml
- web-ingress.yaml
